### ISSUE TITLE
x1 model

### ISSUE THREAD

**Issue by CuddleSabe** [Zj-BinXia/DiffIR#11]
hi, can u release the x1 real-sr model? thanks

**Comment by Zj-BinXia** [comment]
upload it

**Comment by CuddleSabe** [comment]
> upload it

hi, is it the best ckpt? I test it and found it can't resolve the noise in REDS val set..

**Comment by Zj-BinXia** [comment]
You can use v2 model：https://drive.google.com/drive/folders/1goG_l6S0EjK2383UVzXxwLInw-O_SLwO?usp=drive_link

**Comment by Zj-BinXia** [comment]
[DiffIRS2-GANx1](https://drive.google.com/drive/folders/154TGJ7wPSQKmhZBXH4ujLFk3WG_VyClV?usp=drive_link) pursues fidelity while [DiffIRS2-GANx1-V2](https://drive.google.com/drive/folders/1goG_l6S0EjK2383UVzXxwLInw-O_SLwO?usp=drive_link) pursues visual quality and has better denoising ability.

**Comment by CuddleSabe** [comment]
> [DiffIRS2-GANx1](https://drive.google.com/drive/folders/154TGJ7wPSQKmhZBXH4ujLFk3WG_VyClV?usp=drive_link) pursues fidelity while [DiffIRS2-GANx1-V2](https://drive.google.com/drive/folders/1goG_l6S0EjK2383UVzXxwLInw-O_SLwO?usp=drive_link) pursues visual quality and has better denoising ability.
I used the V2 model, I found it can perform well on less degrade case, like fig 1. but can't do well on fig2, the fig3 is the res of the fig2..
fig1
<img width="1472" alt="截屏2023-09-27 11 09 11" src="https://github.com/Zj-BinXia/DiffIR/assets/61224076/c482e1e7-4637-4252-b813-5575d1c90e32">
fig2
<img width="700" alt="截屏2023-09-27 11 18 26" src="https://github.com/Zj-BinXia/DiffIR/assets/61224076/38415d73-e4a3-44b5-b611-43770d6e8ac8">
fig3
<img width="877" alt="截屏2023-09-27 11 08 55" src="https://github.com/Zj-BinXia/DiffIR/assets/61224076/7c5ad635-9602-4d59-97c7-5bca98ca89d3">

**Comment by Zj-BinXia** [comment]
you can try to first perform 4x diffir-ganv2 and then resize (using bicubic) output to original size

**Comment by Zj-BinXia** [comment]
Thanks for your feedback, I think 1x model can be fine-tuned on more severe training degradation to adapt to this situation
