### ISSUE TITLE
想问一下，为什么不能直接将Z和D用来调制bakcbone，而是要分别添加扩散和去噪过程？

### ISSUE THREAD

**Issue by CuddleSabe** [Zj-BinXia/DiffIR#14]
我觉得如果不用diffusion和danoise，而是使用您的KDSR中的KD约束或者更简单的linear+l1约束，是否也能起到差不都的效果。DiffIR中的diffusion究竟起到了多大的作用？谢谢！

I think if you don't use diffusion and denoise, but use the KD constraint in your KDSR or the simpler linear+l1 constraint, will it have similar effects? What role does diffusion in DiffIR play? Thanks!

**Comment by Zj-BinXia** [comment]
Take a look at Figure 4 of the paper, DiffIRS2-V1 and DiffIRS2-V3. Using diffusion can further bring a gain of 0.5 FID. The noise modeling of Diffusion brings strong generation ability, which can further improve visual quality while ensuring that low-frequency information is not damaged
