### ISSUE TITLE
Only Test in SRGAN

### ISSUE THREAD

**Issue by yxldd** [Zj-BinXia/DiffIR#18]
Because of the limitation of computing resources, I want to just use the pre-trained model and test on my privative datasheet, but I put the model in the ./experiment and modify the test_DiffIRS2_GAN_x4.yml, but when I run test.sh, it said
"Traceback (most recent call last):
  File "D:\DL_ws\DiffIR-SRGAN\test.py", line 15, in <module>
    test_pipeline(root_path)
  File "E:\Develop\Anaconda\envs\dl_envs\Lib\site-packages\basicsr\test.py", line 40, in test_pipeline
    model.validation(test_loader, current_iter=opt['name'], tb_logger=None, save_img=opt['val']['save_img'])
  File "E:\Develop\Anaconda\envs\dl_envs\Lib\site-packages\basicsr\models\base_model.py", line 48, in validation
    self.nondist_validation(dataloader, current_iter, tb_logger, save_img)
  File "D:\DL_ws\DiffIR-SRGAN\DiffIR\models\DiffIR_GAN_S2_model.py", line 74, in nondist_validation
    super(DiffIRGANS2Model, self).nondist_validation(dataloader, current_iter, tb_logger, save_img)
  File "E:\Develop\Anaconda\envs\dl_envs\Lib\site-packages\basicsr\models\sr_model.py", line 156, in nondist_validation
    self.feed_data(val_data)
  File "E:\Develop\Anaconda\envs\dl_envs\Lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "D:\DL_ws\DiffIR-SRGAN\DiffIR\models\DiffIR_GAN_S2_model.py", line 65, in feed_data
    self.gt = data['gt'].to(self.device)
              ~~~~^^^^^^
KeyError: 'gt'
"
But isn't it just use SingleImageDataset  and just use LQ as the only input? How can I input ST properly? 
Looking forward to reply.

**Comment by Zj-BinXia** [comment]
I add a [inference_diffir.py](https://github.com/Zj-BinXia/DiffIR/blob/master/DiffIR-SRGAN/inference_diffir.py) under SRGAN folder. You can use it to inference diffir-srgan without GT.

**Comment by yxldd** [comment]
> I add a [inference_diffir.py](https://github.com/Zj-BinXia/DiffIR/blob/master/DiffIR-SRGAN/inference_diffir.py) under SRGAN folder. You can use it to inference diffir-srgan without GT.

Thanks a lot!

**Comment by tzayuan** [comment]
Hi, @Zj-BinXia 
I follow your comment and run `python inference_diffir.py`, the pretrained model is official link provided in [SISR](https://drive.google.com/drive/folders/1Mmhz6Sx9tz-n3QJAd6w-UlxdugTEH2fV), but I got the follow traceback:

```
Traceback (most recent call last):
  File "inference_diffir.py", line 45, in <module>
    loadnet = torch.load(args.model_path, map_location=torch.device('cpu'))
  File "/root/miniconda3/lib/python3.8/site-packages/torch/serialization.py", line 600, in load
    with _open_zipfile_reader(opened_file) as opened_zipfile:
  File "/root/miniconda3/lib/python3.8/site-packages/torch/serialization.py", line 242, in __init__
    super(_open_zipfile_reader, self).__init__(torch._C.PyTorchFileReader(name_or_buffer))
RuntimeError: PytorchStreamReader failed reading zip archive: failed finding central directory
```

Looking forward to reply.

BRs
zeyuan

**Comment by Zj-BinXia** [comment]
> RuntimeError: PytorchStreamReader failed reading zip archive: failed finding central directory

You file is not downloaded completely， You should download the model again

**Comment by tzayuan** [comment]
@Zj-BinXia , Problem solved, thank you. And I'm curious how do you pinpoint the actual problem that this problem corresponds to? :)

**Comment by tzayuan** [comment]
Hi, @Zj-BinXia 

Sorry to bother you one more time. :( 
I have reimplement your training script for demotionblur on GoPro datasets and 1 single 24GB GPU.

When I set:
```
    num_worker_per_gpu: 1
    batch_size_per_gpu: 2
    mini_batch_sizes: [2,4,2,2,1,1]             # Batch size per gpu
    iters: [92000,80000,38000,33000,33000,24000]
    gt_size: 512   # Max patch size for progressive training
    gt_sizes: [192, 256,320,384,464,512]  # Patch sizes for progressive training.
```
The training process can run successfully.

And then I set: 

```
    num_worker_per_gpu: 1
    batch_size_per_gpu: 4
    mini_batch_sizes: [4,4,2,2,1,1]             # Batch size per gpu
    iters: [92000,80000,38000,33000,33000,24000]
    gt_size: 512   # Max patch size for progressive training
    gt_sizes: [192, 256,320,384,464,512]  # Patch sizes for progressive training.
```

it seems that the training process need 26GB GPU.

Is the GPU memory allocate numbers right? If I have any wrong of setting? Tks.
Besides, what's your GPU type for training in follow yml configure and 8 GPUs?

```
    num_worker_per_gpu: 16
    batch_size_per_gpu: 8
    mini_batch_sizes: [8,4,2,2,1,1]             # Batch size per gpu
    iters: [92000,80000,38000,33000,33000,24000]
    gt_size: 512   # Max patch size for progressive training
    gt_sizes: [192, 256,320,384,464,512]  # Patch sizes for progressive training.
```

BRs 
zeyuan

**Comment by zhaolitc** [comment]
> [@Zj-BinXia](https://github.com/Zj-BinXia) , Problem solved, thank you.问题解决，谢谢。

Hi, I follow the google drive to download three pth files: SISR-DiffIRS1.pth，SISR-DiffIRS2.pth，SISR-DiffIRS2-GAN.pth. Which pth file can be used as thd --model_path? I have test all three file, but no one worked: 
``` bash
lib/python3.10/site-packages/torch/nn/modules/module.py", line 1667, in load_state_dict
    raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
RuntimeError: Error(s) in loading state_dict for DiffIRS2:
	size mismatch for G.patch_embed.proj.weight: copying a param with shape torch.Size([64, 3, 3, 3]) from checkpoint, the shape in current model is torch.Size([64, 12, 3, 3]).
	size mismatch for condition.E.0.weight: copying a param with shape torch.Size([64, 3, 3, 3]) from checkpoint, the shape in current model is torch.Size([64, 12, 3, 3]).
	size mismatch for diffusion.condition.E.0.weight: copying a param with shape torch.Size([64, 3, 3, 3]) from checkpoint, the shape in current model is torch.Size([64, 12, 3, 3]).
```
Thank you!
