### ISSUE TITLE
I found the cpen is "degrade  aware"

### ISSUE THREAD

**Issue by CuddleSabe** [Zj-BinXia/DiffIR#22]
<img width="1175" alt="截屏2023-11-15 17 58 20" src="https://github.com/Zj-BinXia/DiffIR/assets/61224076/2d6468a1-0779-41d5-aa81-4a12af34e41f">

我发现cpen的degrade aware很强

**Comment by CuddleSabe** [comment]
如左图所示，可以很好区分相同图像的不同退化。但是如右图所示，不同图像的相同退化无法很好的聚拢。也就是说cpen并没有完全达到“内容解耦”。请问这个算是缺点吗？

**Comment by CuddleSabe** [comment]
并且我另外注意到，与DiffIR相比，DiffI2I是 y = block(norm(x)) + z而不是DiffIR的y=block(norm(x)*var+mu)。请问这个变化有做过消融吗？谢谢！！

**Comment by Zj-BinXia** [comment]
> 并且我另外注意到，与DiffIR相比，DiffI2I是 y = block(norm(x)) + z而不是DiffIR的y=block(norm(x)*var+mu)。请问这个变化有做过消融吗？谢谢！！

DifI2I does this to balance parameter and performance

**Comment by Zj-BinXia** [comment]
> 如左图所示，可以很好区分相同图像的不同退化。但是如右图所示，不同图像的相同退化无法很好的聚拢。也就是说cpen并没有完全达到“内容解耦”。请问这个算是缺点吗？

I am not sure

**Comment by HuaqingHe** [comment]
> > <img alt="截屏2023-11-15 17 58 20" width="1175" src="https://private-user-images.githubusercontent.com/61224076/283077830-2d6468a1-0779-41d5-aa81-4a12af34e41f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ4NzQ3OTIsIm5iZiI6MTcwNDg3NDQ5MiwicGF0aCI6Ii82MTIyNDA3Ni8yODMwNzc4MzAtMmQ2NDY4YTEtMDc3OS00MWQ1LWFhODEtNGExMmFmMzRlNDFmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTEwVDA4MTQ1MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBjZjg0Y2FiYWUzNDMwMjFmYjA2YmViOGYxOTBmYzU0YzJhNTQxMGNjZjY0NzUxMjJjYmUwNjBkYjY5M2M3YTImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.K_gh-Jl0oQQxwz1SnyIwl5bTnt2CSGc6ZCl5gMlBdM8">
> > 我发现cpen的degrade aware很强
> 
> 请问你是怎么生成这样的图像，并且得到这样的结果？谢谢

用 TSNE能生成类似的图
