### ISSUE TITLE
Question about x0-prediction and noise-prediction

### ISSUE THREAD

**Issue by realPasu** [Zj-BinXia/DiffIR#26]
Thank you so much for your contirbution to the community! Your excellent work really benifits me in my research.

I have a question about the diffusion model you employed in your paper. You mentioned that your model was built to "predict noise" in Sec. 4.2, page 4 and trained by the L1 loss of Z (Eqn. 13 in your paper). However, the code implementation is actually "x0 predition" ([https://github.com/Zj-BinXia/DiffIR/blob/3d8d677a77588666618c139b1693634fe5eb638f/DiffIR-RealSR/ldm/ddpm.py#L43C16-L43C16](url)). Did I misunderstand anything?

Really looking forward to your reply. Thank you again.

**Comment by Zj-BinXia** [comment]
Predicting x0 has a slightly better performance than predicting noise.

**Comment by realPasu** [comment]
> Predicting x0 has a slightly better performance than predicting noise.

Thank you so much for your reply. You can consider revising your paper and update it on arXiv.
