### ISSUE TITLE
关于测试数据的设置问题

### ISSUE THREAD

**Issue by 55Dupup** [Zj-BinXia/DiffIR#31]
如果我想用其他数据集来测试 比如一些LMDB类型的数据来测试或者训练 我该如何修改数据集的参数设置呢？
![image](https://github.com/Zj-BinXia/DiffIR/assets/55137390/3df6679b-ff0f-455e-9879-364f9f11ad7f)

**Comment by Zj-BinXia** [comment]
hi, you can change the type from "disk" to "lmdb"

**Comment by 55Dupup** [comment]
Thank you for your reply, do I need to make any other changes? For example, these three parameters.
![image](https://github.com/Zj-BinXia/DiffIR/assets/55137390/850ddac0-e2dc-4244-8141-759705055818)

**Comment by Zj-BinXia** [comment]
That's OK
