### ISSUE TITLE
Finetuning the Inpainting pretrained model

### ISSUE THREAD

**Issue by hanhan3344** [Zj-BinXia/DiffIR#49]
I want to try finetuning the pretrained inpainting model to have a better performance on my privative data, but I have no idea how to load the pretrained model. I would be very grateful if you could provide some guidance.

**Comment by Zj-BinXia** [comment]
Hi, I recommend Big-DiffIRS2-place (https://drive.google.com/drive/folders/1XsJENVezLCa6DFfz5XmhtPKObuMJ9EDa?usp=drive_link)

**Comment by hanhan3344** [comment]
Thank you for your answer, I have solved it!
