### ISSUE TITLE
找不到placebigdata-ta.pth

### ISSUE THREAD

**Issue by Chzhiyuan512** [Zj-BinXia/DiffIR#55]
当我尝试测试inpainting的效果的时候，我下载了作者发布的预训练参数，在运行的时候会报错
`FileNotFoundError: [Errno 2] No such file or directory: '/mnt/bn/xiabinpaint/ICCV-Inpainting/KDSR-inpainting-lightv2/placebigdata-ta.pth'`
排查发现这个路径是在下载的DiffIR's Pretrained Models的config.yaml中定义的，我应该如何获得placebigdata-ta.pth呢

**Comment by Chzhiyuan512** [comment]
是否只需要注释掉config.yaml中的generatorS2_path和generatorS1_path即可

**Comment by Zj-BinXia** [comment]
是的，把config.yaml的generatorS2_path和generatorS1_path注释掉

**Comment by Chzhiyuan512** [comment]
感谢回复
