### ISSUE TITLE
not found ./experiments folder

### ISSUE THREAD

**Issue by abdusa1am** [Zj-BinXia/DiffIR#7]
I want to use directly your pretrain model, you said in readme `Download the pre-trained [model](https://drive.google.com/drive/folders/1JWYaP9VVPX_Mh2w1Vezn74hck-oWSyMh?usp=drive_link) and place it in ./experiments/` but there is no ./experiments folder.

**Comment by Zj-BinXia** [comment]
you can create it by yourself

**Comment by abdusa1am** [comment]
> you can create it by yourself

OK, thanks for your reply. By the way, I want to know how much time you spent to train super resolution, inpainting and deblurring, respectively? You said that you used 8 GPU card, what type of GPU card? V100 or A100?

**Comment by Zj-BinXia** [comment]
V100

**Comment by abdusa1am** [comment]
> 

How much time do you spent to train super resolution, inpainting and deblurring, respectively with 8 V100 gpu card?

**Comment by Zj-BinXia** [comment]
about 6-10 days

**Comment by abdusa1am** [comment]
when i run pip.sh, it stuck on `pip install basicsr --index-url http://pypi.douban.com/simple --trusted-host pypi.douban.com` this command. even if i use vpn or not, it alway stuck. I wonder did you reproduced all steps in your readme before you submit the code?

**Comment by ShijianXu** [comment]
you can simply try pip install basicsr. They just used a mirror source

**Comment by abdusa1am** [comment]
> you can simply try pip install basicsr. They just used a mirror source

你可以创建新的conda环境来试图安装basicsr，无论怎么样它会一直卡住，不会装basicsr，我换了各种镜像，都不行。
