### ISSUE TITLE
RealSR has no folder basicsr

### ISSUE THREAD

**Issue by AndrewWilesRG** [Zj-BinXia/DiffIR#8]
the inference [ inference_diffif.py](https://github.com/Zj-BinXia/DiffIR/blob/master/DiffIR-RealSR/inference_diffir.py) needs a basic  folder named basicsr

**Comment by Zj-BinXia** [comment]
pip install basicsr

**Comment by AndrewWilesRG** [comment]
the line 13 in inference_diffir.py "from basicsr.archs.S2_arch import DiffIRS2" raises an error " Cannot find reference 'S2_arch' in '__init__.py'",  but if I use the DiffIR to replace the basicsr， it seems work

**Comment by Zj-BinXia** [comment]
You can check  inference_diffir.py. It seems that line 13 in inference_diffir.py is "from DiffIR.archs.S2_ arch import DiffIRS2".

**Comment by AndrewWilesRG** [comment]
thank you! it's my typos
